specVersion: 0.2.0
name: moonbeam-dictionary
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws
  chaintypes:
    file: ./dist/chaintypes.js

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler

  - kind: substrate/Moonbeam
    startBlock: 1141492
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvmTransaction
          kind: substrate/MoonbeamCall
